red-channel-input: {'class': 'Directory', 'path': 'demo/cwl-workflows/raster/S2B_MSIL2A_20200209T004659_N0214_R102_T53HPA_20200209T022720'}
green-channel-input: {'class': 'Directory', 'path': 'demo/cwl-workflows/raster/S2B_MSIL2A_20200209T004659_N0214_R102_T53HPA_20200209T022720'}
blue-channel-input: {'class': 'Directory', 'path': 'demo/cwl-workflows/raster/S2B_MSIL2A_20200209T004659_N0214_R102_T53HPA_20200209T022720'}
red-band: 'red'
green-band: 'green'
blue-band: 'blue'
resolution: 'highest'
aoi: 'POLYGON((136.707 -35.991,136.707 -35.804,137.071 -35.804,137.071 -35.991,136.707 -35.991))'
color: 'Gamma RGB 3.5 Saturation 1.4 Sigmoidal RGB 15 0.45'
profile: 'composite'
context: {'class': 'Directory', 'path': '/workspace/scombi-do'}
dockerfile: {'class': 'File', 'path': '.docker/Dockerfile'}